### PR TITLE
Solve the issue of geojson attribute visualization

### PR DESCRIPTION
**Pull request by natsuapo**
The issue is mentioned here: https://github.com/mattijn/topojson/issues/146

I modify the `extract` part. I think it can pass most of the test. But I am not sure whether there are still potential fails.

### CODE REVIEW

**Comment by natsuapo** [comment]
I found that this version of topojson cannot be read by some topojson libraries like the JavaScript one. I thought it is something wrong in my code but I find that the original one cannot do that too. 🤔

**Comment by mattijn** [comment]
Thanks, this is great. Much appreciated

**Comment by mattijn** [comment]
Hm, a bit too quick. There were indeed still some tests failing. I cannot decipher upon first glance if these are false flags, but before this PR all tests were still passing.

**Comment by mattijn** [comment]
I've reverted my merging. I'm not sure exactly if you still can add commits to this PR or if you have to open a new PR, since this is marked as merged.

**Comment by natsuapo** [comment]
I am sorry, I thought the test failing was just the path problem. I will test more.

**Pull request merged**
